#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : libICE
Version  : 1.0.9
Release  : 9
URL      : http://xorg.freedesktop.org/releases/individual/lib/libICE-1.0.9.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libICE-1.0.9.tar.gz
Source99 : http://xorg.freedesktop.org/releases/individual/lib/libICE-1.0.9.tar.gz.sig
Summary  : X Inter Client Exchange Library
Group    : Development/Tools
License  : MIT-Opengroup
Requires: libICE-lib
Requires: libICE-doc
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(32xproto)
BuildRequires : pkgconfig(32xtrans)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)
BuildRequires : pkgconfig(xtrans)
BuildRequires : xmlto

%description
libICE - Inter-Client Exchange Library
Documentation for this API can be found in the doc directory of the source
code, or online at:

%package dev
Summary: dev components for the libICE package.
Group: Development
Requires: libICE-lib
Provides: libICE-devel

%description dev
dev components for the libICE package.


%package dev32
Summary: dev32 components for the libICE package.
Group: Default
Requires: libICE-lib32
Requires: libICE-dev

%description dev32
dev32 components for the libICE package.


%package doc
Summary: doc components for the libICE package.
Group: Documentation

%description doc
doc components for the libICE package.


%package lib
Summary: lib components for the libICE package.
Group: Libraries

%description lib
lib components for the libICE package.


%package lib32
Summary: lib32 components for the libICE package.
Group: Default

%description lib32
lib32 components for the libICE package.


%prep
%setup -q -n libICE-1.0.9
pushd ..
cp -a libICE-1.0.9 build32
popd

%build
export LANG=C
export SOURCE_DATE_EPOCH=1484411086
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1484411086
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/ICE/ICE.h
/usr/include/X11/ICE/ICEconn.h
/usr/include/X11/ICE/ICElib.h
/usr/include/X11/ICE/ICEmsg.h
/usr/include/X11/ICE/ICEproto.h
/usr/include/X11/ICE/ICEutil.h
/usr/lib64/libICE.so
/usr/lib64/pkgconfig/ice.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libICE.so
/usr/lib32/pkgconfig/32ice.pc
/usr/lib32/pkgconfig/ice.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/libICE/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libICE.so.6
/usr/lib64/libICE.so.6.3.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libICE.so.6
/usr/lib32/libICE.so.6.3.0
