#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libICE
Version  : 1.0.9
Release  : 5
URL      : http://xorg.freedesktop.org/releases/individual/lib/libICE-1.0.9.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libICE-1.0.9.tar.gz
Summary  : X Inter Client Exchange Library
Group    : Development/Tools
License  : MIT-Opengroup
Requires: libICE-lib
Requires: libICE-doc
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(xproto)
BuildRequires : pkgconfig(xtrans)
BuildRequires : xmlto

%description
libICE - Inter-Client Exchange Library
Documentation for this API can be found in the doc directory of the source
code, or online at:

%package dev
Summary: dev components for the libICE package.
Group: Development
Requires: libICE-lib

%description dev
dev components for the libICE package.


%package doc
Summary: doc components for the libICE package.
Group: Documentation

%description doc
doc components for the libICE package.


%package lib
Summary: lib components for the libICE package.
Group: Libraries

%description lib
lib components for the libICE package.


%prep
%setup -q -n libICE-1.0.9

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/ICE/ICE.h
/usr/include/X11/ICE/ICEconn.h
/usr/include/X11/ICE/ICElib.h
/usr/include/X11/ICE/ICEmsg.h
/usr/include/X11/ICE/ICEproto.h
/usr/include/X11/ICE/ICEutil.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/libICE/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
